[package]
name = "RDO Grupo"
package_name = "com.acival.rdogrupo"
version = "1.0.1"
build_number = 2


[android]
# 👇 Permissões formatadas como lista para o Android reconhecer corretamente 👇
permissions = ["android.permission.WRITE_EXTERNAL_STORAGE", "android.permission.READ_EXTERNAL_STORAGE", "android.permission.MANAGE_EXTERNAL_STORAGE"]